version: '3.3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - /note-wing/db:/var/lib/mysql
    ports:
      - "3306:3306" # local:container

